### ISSUE TITLE
Plex Assistant fails to initialize if Plex has disabled/empty Music library

### ISSUE THREAD

**Issue by skawt-tee** [maykar/plex_assistant#106]
Plex Assistant version: v1.1.4
Plex Version: 1.21.4.4079
Home Assistant Version: 2021.2.3

Error on start of Home Assistant:
```
2021-02-28 17:02:15 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry MEDIA-SERVER for plex_assistant
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 239, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/plex_assistant/__init__.py", line 76, in async_setup_entry
    pa = await hass.async_add_executor_job(pa_executor, server, list(start_script.keys()))
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/plex_assistant/__init__.py", line 72, in pa_executor
    _pa = PlexAssistant(_server, start_script_keys)
  File "/config/custom_components/plex_assistant/plex_assistant.py", line 14, in __init__
    self.music_id = self.get_section_id("artist")
  File "/config/custom_components/plex_assistant/plex_assistant.py", line 43, in get_section_id
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 239, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/plex_assistant/__init__.py", line 76, in async_setup_entry
    pa = await hass.async_add_executor_job(pa_executor, server, list(start_script.keys()))
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/plex_assistant/__init__.py", line 72, in pa_executor
    _pa = PlexAssistant(_server, start_script_keys)
  File "/config/custom_components/plex_assistant/plex_assistant.py", line 14, in __init__
    return self.library.search(libtype=section, limit=1)[0].librarySectionID
IndexError: list index out of range
    self.music_id = self.get_section_id("artist")
  File "/config/custom_components/plex_assistant/plex_assistant.py", line 43, in get_section_id
    return self.library.search(libtype=section, limit=1)[0].librarySectionID
IndexError: list index out of range
```

----------------------------
Testing/fix:

- Initially noted this upon trying to test/use PA for the first time; I had installed/configured the integration quite some time ago but never got around to actually using it.
- When I first used it, it failed. The logs pointed me to 'plex_assistant.command' service not being present. On further review I noted the above error when Plex was booting.
- I have *always* had 'Music' removed/disabled in Plex Media server as I only use it for video content.

Fix:
- Attempt1 (fail): Re-enable/enable the Music library; pointing at empty directory. No change; same boot error.
- Attempt2 (success): Place single MP3 file in Music library location; after having Plex scan the library and confirming the MP3 was being seen in Plex, Home Assistant no longer reported the above error on boot and PA started to work as expected.

**Comment by maykar** [comment]
Thanks, should be good in 1.1.5

**Comment by skawt-tee** [comment]
Updated to v 1.1.5, removed my Music library from Plex & rebooted - no errors!

Can confirm that issue appears resolved; thanks for the quick fix!
