### ISSUE TITLE
Cannot call service manually or in automation

### ISSUE THREAD

**Issue by RyanEwen** [maykar/plex_assistant#111]
I am getting an error `Failed to call service plex_assistant/command. 'NoneType' object has no attribute 'strip'` when calling the service with a command, such as this:

```yaml
service: plex_assistant.command
command: "Play random futurama"
````

Not sure if this is a bug or something I'm not doing correctly. Any insight is appreciated! Cheers.

**Comment by RyanEwen** [comment]
Oh, here's some more info from the logs:

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/plex_assistant/__init__.py:91
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 10:08:06 PM (9 occurrences)
Last logged: 10:15:40 PM

[140069648472384] 'NoneType' object has no attribute 'strip'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 137, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1488, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1527, in _execute_service
    await self._hass.async_add_executor_job(handler.job.target, service_call)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/plex_assistant/__init__.py", line 91, in handle_input
    command = call.data.get("command").strip()
AttributeError: 'NoneType' object has no attribute 'strip'
```

**Comment by maykar** [comment]
```
service: plex_assistant.command
data:
  command: "Play random futurama"
```

**Comment by RyanEwen** [comment]
Yep, I'm an idiot. Thank you!
