### ISSUE TITLE
Unable to install rapidfuzz

### ISSUE THREAD

**Issue by VPsych** [maykar/plex_assistant#117]
Running the latest Home Assistant version 2021.4.0 through Docker on my Synology NAS. Home Assistant reports that it cannot install rapidfuzz v1.1.1 and therefore cannot run Plex Assistant. 

This seems to be a more recent change as I had it working a few months back. It might be an older version of Python but shouldn't that all be taken care of by using the latest HASS.io docker image? Home Assistant is reporting Python Version	3.8.7.

```

Logger: homeassistant.util.package
Source: util/package.py:96 
First occurred: 10:06:41 AM (2 occurrences) 
Last logged: 10:09:14 AM

Unable to install package rapidfuzz==1.1.1: ERROR: Command errored out with exit status 1: command: /usr/local/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-a2erun5w/rapidfuzz/setup.py'"'"'; __file__='"'"'/tmp/pip-install-a2erun5w/rapidfuzz/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-nsdsn0eq cwd: /tmp/pip-install-a2erun5w/rapidfuzz/ Complete output (33 lines): running bdist_wheel running build running build_py creating build creating build/lib.linux-x86_64-3.8 creating build/lib.linux-x86_64-3.8/rapidfuzz copying src/rapidfuzz/utils.py -> build/lib.linux-x86_64-3.8/rapidfuzz copying src/rapidfuzz/fuzz.py -> build/lib.linux-x86_64-3.8/rapidfuzz copying src/rapidfuzz/__init__.py -> build/lib.linux-x86_64-3.8/rapidfuzz copying src/rapidfuzz/levenshtein.py -> build/lib.linux-x86_64-3.8/rapidfuzz copying src/rapidfuzz/process.py -> build/lib.linux-x86_64-3.8/rapidfuzz copying src/rapidfuzz/string_metric.py -> build/lib.linux-x86_64-3.8/rapidfuzz running egg_info writing src/rapidfuzz.egg-info/PKG-INFO writing dependency_links to src/rapidfuzz.egg-info/dependency_links.txt writing top-level names to src/rapidfuzz.egg-info/top_level.txt reading manifest file 'src/rapidfuzz.egg-info/SOURCES.txt' reading manifest template 'MANIFEST.in' warning: no files found matching '*.txx' under directory 'src/rapidfuzz-cpp/rapidfuzz' warning: no previously-included files found matching 'src/rapidfuzz-cpp/rapidfuzz/process.hpp' warning: no previously-included files found matching 'src/rapidfuzz-cpp/rapidfuzz/process.txx' warning: no files found matching '*' under directory 'extern/variant' writing manifest file 'src/rapidfuzz.egg-info/SOURCES.txt' running build_ext building 'rapidfuzz.cpp_process' extension creating build/temp.linux-x86_64-3.8 creating build/temp.linux-x86_64-3.8/src creating build/temp.linux-x86_64-3.8/src/rapidfuzz-cpp creating build/temp.linux-x86_64-3.8/src/rapidfuzz-cpp/rapidfuzz creating build/temp.linux-x86_64-3.8/src/rapidfuzz-cpp/rapidfuzz/details gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fno-semantic-interposition -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -ljemalloc -DTHREAD_STACK_SIZE=0x100000 -fPIC -Isrc/rapidfuzz-cpp/ -I/usr/local/include/python3.8 -c src/cpp_process.cpp -o build/temp.linux-x86_64-3.8/src/cpp_process.o -O3 -std=c++11 -Wextra -Wall -DVERSION_INFO="1.1.1" unable to execute 'gcc': No such file or directory error: command 'gcc' failed with exit status 1 ---------------------------------------- ERROR: Failed building wheel for rapidfuzz ERROR: Command errored out with exit status 1: command: /usr/local/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-a2erun5w/rapidfuzz/setup.py'"'"'; __file__='"'"'/tmp/pip-install-a2erun5w/rapidfuzz/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-m06iiwzi/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/rapidfuzz cwd: /tmp/pip-install-a2erun5w/rapidfuzz/ Complete output (33 lines): running install running build running build_py creating build creating build/lib.linux-x86_64-3.8 creating build/lib.linux-x86_64-3.8/rapidfuzz copying src/rapidfuzz/utils.py -> build/lib.linux-x86_64-3.8/rapidfuzz copying src/rapidfuzz/fuzz.py -> build/lib.linux-x86_64-3.8/rapidfuzz copying src/rapidfuzz/__init__.py -> build/lib.linux-x86_64-3.8/rapidfuzz copying src/rapidfuzz/levenshtein.py -> build/lib.linux-x86_64-3.8/rapidfuzz copying src/rapidfuzz/process.py -> build/lib.linux-x86_64-3.8/rapidfuzz copying src/rapidfuzz/string_metric.py -> build/lib.linux-x86_64-3.8/rapidfuzz running egg_info writing src/rapidfuzz.egg-info/PKG-INFO writing dependency_links to src/rapidfuzz.egg-info/dependency_links.txt writing top-level names to src/rapidfuzz.egg-info/top_level.txt reading manifest file 'src/rapidfuzz.egg-info/SOURCES.txt' reading manifest template 'MANIFEST.in' warning: no files found matching '*.txx' under directory 'src/rapidfuzz-cpp/rapidfuzz' warning: no previously-included files found matching 'src/rapidfuzz-cpp/rapidfuzz/process.hpp' warning: no previously-included files found matching 'src/rapidfuzz-cpp/rapidfuzz/process.txx' warning: no files found matching '*' under directory 'extern/variant' writing manifest file 'src/rapidfuzz.egg-info/SOURCES.txt' running build_ext building 'rapidfuzz.cpp_process' extension creating build/temp.linux-x86_64-3.8 creating build/temp.linux-x86_64-3.8/src creating build/temp.linux-x86_64-3.8/src/rapidfuzz-cpp creating build/temp.linux-x86_64-3.8/src/rapidfuzz-cpp/rapidfuzz creating build/temp.linux-x86_64-3.8/src/rapidfuzz-cpp/rapidfuzz/details gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fno-semantic-interposition -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -ljemalloc -DTHREAD_STACK_SIZE=0x100000 -fPIC -Isrc/rapidfuzz-cpp/ -I/usr/local/include/python3.8 -c src/cpp_process.cpp -o build/temp.linux-x86_64-3.8/src/cpp_process.o -O3 -std=c++11 -Wextra -Wall -DVERSION_INFO="1.1.1" unable to execute 'gcc': No such file or directory error: command 'gcc' failed with exit status 1 ---------------------------------------- ERROR: Command errored out with exit status 1: /usr/local/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-a2erun5w/rapidfuzz/setup.py'"'"'; __file__='"'"'/tmp/pip-install-a2erun5w/rapidfuzz/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-m06iiwzi/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/rapidfuzz Check the logs for full command output. WARNING: You are using pip version 20.2.4; however, version 21.0.1 is available. You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.
Unable to install package glocaltokens==0.3.0: ERROR: Command errored out with exit status 1: command: /usr/local/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-nzlyrh3a/grpcio-tools/setup.py'"'"'; __file__='"'"'/tmp/pip-install-nzlyrh3a/grpcio-tools/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-grjs1jy4 cwd: /tmp/pip-install-nzlyrh3a/grpcio-tools/ Complete output (11 lines): Traceback (most recent call last): File "<string>", line 1, in <module> File "/tmp/pip-install-nzlyrh3a/grpcio-tools/setup.py", line 112, in <module> if check_linker_need_libatomic(): File "/tmp/pip-install-nzlyrh3a/grpcio-tools/setup.py", line 73, in check_linker_need_libatomic cc_test = subprocess.Popen(['cc', '-x', 'c++', '-std=c++11', '-'], File "/usr/local/lib/python3.8/subprocess.py", line 854, in __init__ self._execute_child(args, executable, preexec_fn, close_fds, File "/usr/local/lib/python3.8/subprocess.py", line 1702, in _execute_child raise child_exception_type(errno_num, err_msg, err_filename) FileNotFoundError: [Errno 2] No such file or directory: 'cc' ---------------------------------------- ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output. WARNING: You are using pip version 20.2.4; however, version 21.0.1 is available. You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.

```

**Comment by maxbachmann** [comment]
The relevant part of the error message is:
```
unable to execute 'gcc': No such file or directory error: command 'gcc' f
No such file or directory: 'cc'
```
it appears like on your platform pip does not find a wheel and therefore has to compile rapidfuzz and glocaltokens from source. This requires a compiler to be installed on the system. Possibly your previous attempt either was on a different system which had wheels, or on a system which had a C/C++ compiler available.
A possible solution would be to ask the maintainers of the HASS.io image whether common build tools like gcc (when gcc is available cc often simply links to gcc) could be included in the docker image, since I think this requirement is quite common.

**Comment by maykar** [comment]
I'm unsure as what your issue could be ATM. The wheels for Plex Assistants dependencies included in [HA's wheels for custom integrations.](https://github.com/home-assistant/wheels-custom-integrations/)

**Comment by maykar** [comment]
Sorry for the delayed response. The most likely reason you're having issues is that you are using an [unsupported installation](https://www.home-assistant.io/more-info/unsupported/os/). [More info about unsupported installations (ADR)](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md).

So, short answer would be to either use a supported installation method, follow the ADR guidelines above, or install the needed dependencies to your install manually.

**Comment by yeahme49** [comment]
I'm running the home assistant os, so it's a supported installation method and I'm having the same issue with rapidfuzz. i just got around to trying to update to the latest plex_assistant version and it's not working.

**Comment by kapeer** [comment]
This might as well be fixed already, but I am going to leave a comment anyway for future visitors.

@maxbachmann was right. All I had to do to was execute the following in the docker image
```
apk add gcc g++
pip install rapidfuzz==1.1.1 # This might not be needed, but I did it to test the fix
```
