### ISSUE TITLE
AttributeError: 'list' object has no attribute 'episode'

### ISSUE THREAD

**Issue by dparv** [maykar/plex_assistant#120]
Got this error while trying to play an episode. Apparently the command is posted from IFFFT/Google, but then it errors out with this:

2021-04-28 17:35:32 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall plex_assistant.command (c:453abd1b33caefe7863c48d5f9b7ee82): command=play Shadow and Bone season 1 episode 5 on office TV>
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/homeassistant/core.py", line 1496, in catch_exceptions
    await coro_or_task
  File "/home/ubuntu/.local/lib/python3.8/site-packages/homeassistant/core.py", line 1519, in _execute_service
    await self._hass.async_add_executor_job(handler.job.target, service_call)
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ubuntu/.homeassistant/custom_components/plex_assistant/__init__.py", line 132, in handle_input
    media, offset = filter_media(pa, command, media, library)
  File "/home/ubuntu/.homeassistant/custom_components/plex_assistant/helpers.py", line 203, in filter_media
    media = media.episode(season=int(command["season"] or 1), episode=int(command["episode"]))
AttributeError: 'list' object has no attribute 'episode'

**Comment by dparv** [comment]
Seems that Plex can't detect the episode number if using generic video scanner, however with the TV Shows library type - it seems to work better.

**Comment by zididadaday** [comment]
I have this issue too, library is defined as TV show type, shouldn't be a problem.
I spent the whole day on this one (just installed Plex Assistant and was testing and specific episode didn't work).
It just hit me what the issue was.. will create a new issue for it.
