### ISSUE TITLE
Errors in logs and IFTTT

### ISSUE THREAD

**Issue by wwwescape** [maykar/plex_assistant#127]
My setup is a Raspberry Pi 4 with Home Assistant Container (Docker). My Raspberry Pi is on a static internal IP address: `192.168.0.125`. I've followed the README to the point but I'm getting a few errors. My configuration is IFTTT and Google Assistand.

When I try saying a command, sometimes Google Assistant says that it `can't send messages at the moment` or sometimes it acknowledges the command by does nothing. There are no errors in the Home Assistant logs but I'm guessing that's where the error is with IFTTT (see below screenshot). Do I need a external static IP for this to work?

Also when I use the `plex_assistant.command` service in HA's Developer Tools, I see some errors in the Home Assistant logs but couldn't understand what's wrong.

I can confirm that the Google Cast and Plex Media Server integrations are working too.

* Any errors related to Plex Assistant or Plex in your logs along with debug info
```
2021-05-23 12:33:42 WARNING (MainThread) [homeassistant.loader] You are using a custom integration plex_assistant which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-05-23 12:33:42 WARNING (MainThread) [homeassistant.loader] You are using a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-05-23 12:33:46 WARNING (SyncWorker_4) [homeassistant.components.zeroconf.usage] Detected code that attempted to create another Zeroconf instance. Please use the shared Zeroconf via await homeassistant.components.zeroconf.async_get_instance(hass); Please report this issue
Stack (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/zeroconf/usage.py", line 24, in new_zeroconf_new
    _report(
  File "/usr/src/homeassistant/homeassistant/components/zeroconf/usage.py", line 47, in _report
    _LOGGER.warning(
Stack (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/zeroconf/usage.py", line 24, in new_zeroconf_new
    _report(
  File "/usr/src/homeassistant/homeassistant/components/zeroconf/usage.py", line 47, in _report
    _LOGGER.warning(
2021-05-23 12:34:12 DEBUG (SyncWorker_5) [custom_components.plex_assistant.const] Media titles: 2557
2021-05-23 12:34:39 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'NoneType' object has no attribute 'strip'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 366, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 566, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1481, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1520, in _execute_service
    await self._hass.async_add_executor_job(handler.job.target, service_call)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/plex_assistant/__init__.py", line 91, in handle_input
    command = call.data.get("command").strip()
AttributeError: 'NoneType' object has no attribute 'strip'
2021-05-23 12:34:39 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [2873397104] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 21, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 482, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1212, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 348, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 366, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 566, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1481, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1520, in _execute_service
    await self._hass.async_add_executor_job(handler.job.target, service_call)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/plex_assistant/__init__.py", line 91, in handle_input
    command = call.data.get("command").strip()
AttributeError: 'NoneType' object has no attribute 'strip'
2021-05-23 12:41:43 ERROR (Thread-8) [pychromecast.socket_client] [Master Bedroom TV(192.168.0.103):8009] Error reading from socket.
2021-05-23 12:41:43 WARNING (Thread-8) [pychromecast.socket_client] [Master Bedroom TV(192.168.0.103):8009] Error communicating with socket, resetting connection
2021-05-23 12:41:43 ERROR (Thread-8) [pychromecast.socket_client] [Master Bedroom TV(192.168.0.103):8009] Failed to connect to service ServiceInfo(type='mdns', data='MiTV-AXSO0-56e5b8540d15151f24187b68c3494830._googlecast._tcp.local.'), retrying in 5.0s
```
* The trigger method you're using (IFTTT, DialogFlow, or HA Conversation)
IFTTT
* The method used to install (HACS or manually)
HACS
* If HA's Plex Integration works without issue
Yes
* The command you are using (if the issue is command specific)
Used all types of commands mentioned in the README
* If using the `plex_assistant.command` service in HA's Developer Tools is working
No. See above debug log. Screenshot attached of UI.

![image](https://user-images.githubusercontent.com/651507/119251715-9b192580-bbc5-11eb-9316-614cbddb99c5.png)

* Config options if relevant
N/A
* If you're using advanced config, show the config you're using
N/A

I also see this error in IFTTT's activity log for the applet:
![image](https://user-images.githubusercontent.com/651507/119251669-5ee5c500-bbc5-11eb-8583-a691d436d46a.png)

**Comment by dj21d** [comment]
IFTTT is trying to call your local IP which it definitely can't do. You'll need to setup remote access to your home assistant instance for IFTTT to make those web requests to your system. The two most popular options are if you're paying for nabi casa you get a remote link, or you can setup port forwarding on your router and duckdns. 

Here's a great guide for it https://www.home-assistant.io/docs/configuration/remote/

**Comment by wwwescape** [comment]
Thanks. I'll try those options.
