### ISSUE TITLE
Fails to install dependency and errors on setup

### ISSUE THREAD

**Issue by regulad** [maykar/plex_assistant#142]
When attempting to setup the configuration of Plex Assistant after installing it via HACS, the integration is unable to load the configuration flow after encountering an error with a dependency.
```2021-08-21 12:22:24 ERROR (SyncWorker_6) [homeassistant.util.package] Unable to install package rapidfuzz==1.1.1: ERROR: Command errored out with exit status 1:
command: /usr/local/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-0iafjay3/rapidfuzz/setup.py'"'"'; __file__='"'"'/tmp/pip-install-0iafjay3/rapidfuzz/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-1xhdwabb
cwd: /tmp/pip-install-0iafjay3/rapidfuzz/
Complete output (33 lines):
running bdist_wheel
running build
running build_py
creating build
creating build/lib.linux-x86_64-3.9
creating build/lib.linux-x86_64-3.9/rapidfuzz
copying src/rapidfuzz/levenshtein.py -> build/lib.linux-x86_64-3.9/rapidfuzz
copying src/rapidfuzz/fuzz.py -> build/lib.linux-x86_64-3.9/rapidfuzz
copying src/rapidfuzz/utils.py -> build/lib.linux-x86_64-3.9/rapidfuzz
copying src/rapidfuzz/process.py -> build/lib.linux-x86_64-3.9/rapidfuzz
copying src/rapidfuzz/__init__.py -> build/lib.linux-x86_64-3.9/rapidfuzz
copying src/rapidfuzz/string_metric.py -> build/lib.linux-x86_64-3.9/rapidfuzz
running egg_info
writing src/rapidfuzz.egg-info/PKG-INFO
writing dependency_links to src/rapidfuzz.egg-info/dependency_links.txt
writing top-level names to src/rapidfuzz.egg-info/top_level.txt
reading manifest file 'src/rapidfuzz.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.txx' under directory 'src/rapidfuzz-cpp/rapidfuzz'
warning: no previously-included files found matching 'src/rapidfuzz-cpp/rapidfuzz/process.hpp'
warning: no previously-included files found matching 'src/rapidfuzz-cpp/rapidfuzz/process.txx'
warning: no files found matching '*' under directory 'extern/variant'
adding license file 'LICENSE'
writing manifest file 'src/rapidfuzz.egg-info/SOURCES.txt'
running build_ext
building 'rapidfuzz.cpp_process' extension
creating build/temp.linux-x86_64-3.9
creating build/temp.linux-x86_64-3.9/src
creating build/temp.linux-x86_64-3.9/src/rapidfuzz-cpp
creating build/temp.linux-x86_64-3.9/src/rapidfuzz-cpp/rapidfuzz
creating build/temp.linux-x86_64-3.9/src/rapidfuzz-cpp/rapidfuzz/details
gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fno-semantic-interposition -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -DTHREAD_STACK_SIZE=0x100000 -fPIC -Isrc/rapidfuzz-cpp/ -I/usr/local/include/python3.9 -c src/cpp_process.cpp -o build/temp.linux-x86_64-3.9/src/cpp_process.o -O3 -std=c++11 -Wextra -Wall -DVERSION_INFO="1.1.1"
error: command 'gcc' failed: No such file or directory
----------------------------------------
ERROR: Failed building wheel for rapidfuzz
ERROR: Command errored out with exit status 1:
command: /usr/local/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-0iafjay3/rapidfuzz/setup.py'"'"'; __file__='"'"'/tmp/pip-install-0iafjay3/rapidfuzz/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-sca8exd9/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/rapidfuzz
cwd: /tmp/pip-install-0iafjay3/rapidfuzz/
Complete output (33 lines):
running install
running build
running build_py
creating build
creating build/lib.linux-x86_64-3.9
creating build/lib.linux-x86_64-3.9/rapidfuzz
copying src/rapidfuzz/levenshtein.py -> build/lib.linux-x86_64-3.9/rapidfuzz
copying src/rapidfuzz/fuzz.py -> build/lib.linux-x86_64-3.9/rapidfuzz
copying src/rapidfuzz/utils.py -> build/lib.linux-x86_64-3.9/rapidfuzz
copying src/rapidfuzz/process.py -> build/lib.linux-x86_64-3.9/rapidfuzz
copying src/rapidfuzz/__init__.py -> build/lib.linux-x86_64-3.9/rapidfuzz
copying src/rapidfuzz/string_metric.py -> build/lib.linux-x86_64-3.9/rapidfuzz
running egg_info
writing src/rapidfuzz.egg-info/PKG-INFO
writing dependency_links to src/rapidfuzz.egg-info/dependency_links.txt
writing top-level names to src/rapidfuzz.egg-info/top_level.txt
reading manifest file 'src/rapidfuzz.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.txx' under directory 'src/rapidfuzz-cpp/rapidfuzz'
warning: no previously-included files found matching 'src/rapidfuzz-cpp/rapidfuzz/process.hpp'
warning: no previously-included files found matching 'src/rapidfuzz-cpp/rapidfuzz/process.txx'
warning: no files found matching '*' under directory 'extern/variant'
adding license file 'LICENSE'
writing manifest file 'src/rapidfuzz.egg-info/SOURCES.txt'
running build_ext
building 'rapidfuzz.cpp_process' extension
creating build/temp.linux-x86_64-3.9
creating build/temp.linux-x86_64-3.9/src
creating build/temp.linux-x86_64-3.9/src/rapidfuzz-cpp
creating build/temp.linux-x86_64-3.9/src/rapidfuzz-cpp/rapidfuzz
creating build/temp.linux-x86_64-3.9/src/rapidfuzz-cpp/rapidfuzz/details
gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fno-semantic-interposition -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -DTHREAD_STACK_SIZE=0x100000 -fPIC -Isrc/rapidfuzz-cpp/ -I/usr/local/include/python3.9 -c src/cpp_process.cpp -o build/temp.linux-x86_64-3.9/src/cpp_process.o -O3 -std=c++11 -Wextra -Wall -DVERSION_INFO="1.1.1"
error: command 'gcc' failed: No such file or directory
----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-0iafjay3/rapidfuzz/setup.py'"'"'; __file__='"'"'/tmp/pip-install-0iafjay3/rapidfuzz/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-sca8exd9/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/rapidfuzz Check the logs for full command output.
WARNING: You are using pip version 20.2.4; however, version 21.2.4 is available.
You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.
2021-08-21 12:22:24 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
resp = await self._request_handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 211, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 128, in post
return await super().post(request)
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 63, in wrapper
result = await method(view, request, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 72, in post
result = await self._flow_mgr.async_init(
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 153, in async_init
flow, result = await task
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 171, in _async_init
flow = await self.async_create_flow(handler, context=context, data=data)
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 693, in async_create_flow
await async_process_deps_reqs(self.hass, self._hass_config, integration)
File "/usr/src/homeassistant/homeassistant/setup.py", line 375, in async_process_deps_reqs
await requirements.async_get_integration_with_requirements(
File "/usr/src/homeassistant/homeassistant/requirements.py", line 84, in async_get_integration_with_requirements
await _async_process_integration(hass, integration, done)
File "/usr/src/homeassistant/homeassistant/requirements.py", line 100, in _async_process_integration
await async_process_requirements(
File "/usr/src/homeassistant/homeassistant/requirements.py", line 164, in async_process_requirements
raise RequirementsNotFound(name, [req])
homeassistant.requirements.RequirementsNotFound: Requirements for plex_assistant not found: ['rapidfuzz==1.1.1'].```

**Comment by jassycliq** [comment]
This seems to be an issue with running HA in a container.
I was able to resolve this by connecting to the container then installing `build-base` and `python3-dev`.
Could probably ask Linux.io to add them to the image but not sure how responsive they are to requests like that.

**Comment by zenyatta80** [comment]
> This seems to be an issue with running HA in a container.
> I was able to resolve this by connecting to the container then installing `build-base` and `python3-dev`.
> Could probably ask Linux.io to add them to the image but not sure how responsive they are to requests like that.

Please are you able to share the exact commands you used.

**Comment by jassycliq** [comment]
> > This seems to be an issue with running HA in a container.
> > I was able to resolve this by connecting to the container then installing `build-base` and `python3-dev`.
> > Could probably ask Linux.io to add them to the image but not sure how responsive they are to requests like that.
> 
> Please are you able to share the exact commands you used. 

It's going to depend on the name for your container but it'll be something like:

_docker exec -it {name_of_container_without_braces} /bin/bash_

Then:

_apk add python3-dev build-base_
