### ISSUE TITLE
Unable to install component

### ISSUE THREAD

**Issue by Yostie** [maykar/plex_assistant#157]
I have HA's core integration installed and working, but whenever I try to install Plex Assistant I get the error "Config  flow could not be loaded"  My logs when the error occurs are as below. Plex Assistant was installed through HACS.
```
Logger: aiohttp.server
Source: requirements.py:196
First occurred: 10:15:33 AM (1 occurrences)
Last logged: 10:15:33 AM

Error handling request
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/lib/python3.9/site-packages/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/lib/python3.9/site-packages/homeassistant/components/http/forwarded.py", line 220, in forwarded_middleware
    return await handler(request)
  File "/usr/lib/python3.9/site-packages/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/lib/python3.9/site-packages/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/lib/python3.9/site-packages/homeassistant/components/http/auth.py", line 181, in auth_middleware
    return await handler(request)
  File "/usr/lib/python3.9/site-packages/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/lib/python3.9/site-packages/homeassistant/components/config/config_entries.py", line 130, in post
    return await super().post(request)
  File "/usr/lib/python3.9/site-packages/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
  File "/usr/lib/python3.9/site-packages/homeassistant/data_entry_flow.py", line 203, in async_init
    flow, result = await task
  File "/usr/lib/python3.9/site-packages/homeassistant/data_entry_flow.py", line 221, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/lib/python3.9/site-packages/homeassistant/config_entries.py", line 715, in async_create_flow
    await async_process_deps_reqs(self.hass, self._hass_config, integration)
  File "/usr/lib/python3.9/site-packages/homeassistant/setup.py", line 353, in async_process_deps_reqs
    await requirements.async_get_integration_with_requirements(
  File "/usr/lib/python3.9/site-packages/homeassistant/requirements.py", line 85, in async_get_integration_with_requirements
    await _async_process_integration(hass, integration, done)
  File "/usr/lib/python3.9/site-packages/homeassistant/requirements.py", line 101, in _async_process_integration
    await async_process_requirements(
  File "/usr/lib/python3.9/site-packages/homeassistant/requirements.py", line 164, in async_process_requirements
    await _async_process_requirements(
  File "/usr/lib/python3.9/site-packages/homeassistant/requirements.py", line 196, in _async_process_requirements
    raise RequirementsNotFound(name, [req])
homeassistant.requirements.RequirementsNotFound: Requirements for plex_assistant not found: ['rapidfuzz==1.1.1'].
```

**Comment by Yostie** [comment]
Same issue as #142 .  Problem has been solved now.
