### ISSUE TITLE
Failed to call service plex_assistant/command. generator raised StopIteration

### ISSUE THREAD

**Issue by nikiyao** [maykar/plex_assistant#31]
I keep getting this error when I send a command, and my assistant devices also keep telling me that they can't control plex yet

**Comment by nikiyao** [comment]
this is what I see in my logs

```

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1260, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1299, in _execute_service
    await self._hass.async_add_executor_job(handler.func, service_call)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/plex_assistant/__init__.py", line 127, in handle_input
    command = process_speech(command_string, localize, default_cast, PA)
  File "/config/custom_components/plex_assistant/process_speech.py", line 25, in process_speech
    fuzz_client = fuzzy(control_check, devices)
  File "/config/custom_components/plex_assistant/helpers.py", line 42, in fuzzy
    return fw.extractOne(media, lib, scorer=scorer)
  File "/usr/local/lib/python3.7/site-packages/fuzzywuzzy/process.py", line 245, in extractOne
    return max(best_list, key=lambda i: i[1])
RuntimeError: generator raised StopIteration
```

**Comment by nikiyao** [comment]
reinstalled and it got rid of that error
