### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'clients'

### ISSUE THREAD

**Issue by freakshock88** [maykar/plex_assistant#44]
I just installed and configured Plex Assistant for the first time. 
I get this error in my HA logbook:

```
Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 1680, in run
    self._service_state_changed.fire(
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 1438, in fire
    h(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 1536, in on_change
    listener.add_service(*args)
  File "/usr/local/lib/python3.8/site-packages/pychromecast/discovery.py", line 65, in add_service
    self._add_update_service(zconf, typ, name, self.add_callback)
  File "/usr/local/lib/python3.8/site-packages/pychromecast/discovery.py", line 123, in _add_update_service
    callback(uuid, name)
  File "/usr/local/lib/python3.8/site-packages/pychromecast/__init__.py", line 242, in internal_callback
    callback(
  File "/config/custom_components/plex_assistant/helpers.py", line 17, in cc_callback
    PA.clients = PA.server.clients()
AttributeError: 'NoneType' object has no attribute 'clients'
```

My config: 

```
plex_assistant:
  url: 'REDACTED'
  token: 'REDACTED'
  default_cast: 'PlexKodi TV'
  language: 'en'
  tts_errors: true
```

I do however see client devices in my companion sensor, including the one I set as default_cast.

Any idea what's happening here?

**Comment by maykar** [comment]
Seems like it's unable to connect to your Plex Server. Double check the URL and token, make sure you're using https if you have it set in Plex's settings or even set `Allow fallback to insecure connections` to`on same network` or `always` depending on your setup

**Comment by maykar** [comment]
I need to add some checks/errors for such cases in the future, but that's where I would start.

**Comment by freakshock88** [comment]
I checked the Secure connections setting, it is set to `preferred`. I'm using a HTTPS url in my config. When I use: `https://plexapp.mydomain.com/clients?X-Plex-Token=MYTOKEN` the client that I'm trying to use also shows up in the response reliably. Guess it's hard to debug now. Ah well, I'll try again later. Thanks for your response!

**Comment by maykar** [comment]
So it's working, but you're occasionally getting this error? Also, since you're set to `preferred` you can always set the url to http instead of https and see if it makes a difference.

**Comment by freakshock88** [comment]
I was able to solve the error now by using a http local URL instead of my external domain. 
Thanks for your help!
