### ISSUE TITLE
Create() got an unexpected keyword argument 'startItem'

### ISSUE THREAD

**Issue by swavans** [maykar/plex_assistant#53]
First of, this is an awesome project and I have actually been looking for this for a while. Great Job.
I just installed Home Assistant and added HACS and your plugin solely for this.

I create a simple service with the command:
"Play Die Hard on Living Room TV" 
The chromecast starts and is connecting to plex however the film itself is not starting. 
I found the following errors in the logs.

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 137, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1315, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1354, in _execute_service
    await self._hass.async_add_executor_job(handler.func, service_call)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/plex_assistant/__init__.py", line 217, in handle_input
    plex_c.block_until_playing(media)
  File "/usr/local/lib/python3.8/site-packages/pychromecast/controllers/plex.py", line 433, in block_until_playing
    self.play_media(media, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pychromecast/controllers/plex.py", line 453, in play_media
    self.launch(app_launched_callback)
  File "/usr/local/lib/python3.8/site-packages/pychromecast/controllers/__init__.py", line 44, in launch
    self._socket_client.receiver_controller.launch_app(
  File "/usr/local/lib/python3.8/site-packages/pychromecast/socket_client.py", line 1183, in launch_app
    self._send_launch_message(app_id, force_launch, callback_function)
  File "/usr/local/lib/python3.8/site-packages/pychromecast/socket_client.py", line 1198, in _send_launch_message
    callback_function()
  File "/usr/local/lib/python3.8/site-packages/pychromecast/controllers/plex.py", line 449, in app_launched_callback
    self._send_start_play(media, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pychromecast/controllers/plex.py", line 406, in _send_start_play
    msg = media_to_chromecast_command(
  File "/usr/local/lib/python3.8/site-packages/pychromecast/controllers/plex.py", line 114, in media_to_chromecast_command
    playQueue = server.createPlayQueue(media, startItem=startItem)
  File "/usr/local/lib/python3.8/site-packages/plexapi/server.py", line 289, in createPlayQueue
    return PlayQueue.create(self, item, **kwargs)
TypeError: create() got an unexpected keyword argument 'startItem'
```

I can also see the requests comming in in the server logs without any errors:

```
Oct 01, 2020 11:51:09.405 [7622] Debug — Auth: authenticated user 1 as ******@gmail.com
Oct 01, 2020 11:51:09.405 [32601] Debug — Request: [192.168.2.19:35678 (Subnet)] GET /clients (5 live) GZIP Signed-in Token (******@gmail.com)
Oct 01, 2020 11:51:09.405 [7621] Debug — Completed: [192.168.2.19:35678] 200 GET /clients (5 live) GZIP 0ms 397 bytes (pipelined: 1)
Oct 01, 2020 11:51:10.401 [7621] Debug — Auth: authenticated user 1 as ******@gmail.com
Oct 01, 2020 11:51:10.402 [32601] Debug — Request: [192.168.2.19:35678 (Subnet)] GET /library/all?limit=1&sort=addedAt%3Adesc (5 live) GZIP Signed-in Token (******@gmail.com)
Oct 01, 2020 11:51:10.408 [7622] Debug — Completed: [192.168.2.19:35678] 200 GET /library/all?limit=1&sort=addedAt%3Adesc (5 live) GZIP 6ms 739 bytes (pipelined: 2)
```

Would be really happy if you could point me in the right direction.

Home Assistant Version:  0.115.6
Plex (Home Assistant) Version: 2.4.6
Plex Assistant version: 0.2.9
Plex Server: NVIDIA Shield
Plex Server Version: 4.43.1

**Comment by maykar** [comment]
You're not the first to report this. Somehow the Pychromecast library is getting updated on some systems, which it shouldn't be until 0.116. The issue is the updated Pychromecast calls require an updated PlexAPI as well.

For now in custom_components/plex_assistant you can edit the manifest.json file with the info below:
```
{
  "domain": "plex_assistant",
  "name": "Plex Assistant",
  "documentation": "https://github.com/maykar/plex_assistant",
  "dependencies": [],
  "codeowners": ["@maykar"],
  "requirements": [
    "gTTs",
    "pychromecast>=7.4.1",
    "fuzzywuzzy",
    "plexapi>=4.1.1"
  ]
}
```

Delete the __pycache__ folder in there as well to be safe and restart. Let me know if that fixes the issue.

**Comment by maykar** [comment]
0.3.0 should fix the issue, it will bump plexapi and pychromecast to their needed versions

**Comment by swavans** [comment]
Great, thnx so much. Sorry for the duplicate

**Comment by maykar** [comment]
No worries at all
