### ISSUE TITLE
Cant play on Plex Clients(Android tv app)

### ISSUE THREAD

**Issue by Drauboss** [maykar/plex_assistant#62]
I cant play on Plex clients like the android tv app or on the Plex Website. Playing on Chromecasts is working fine.
It definetly worked on version 0.2.4, all the versions after that im not sure because i didnt used the Integration since than.
Thats what i got in the logs:

```
Logger: homeassistant.components.websocket_api.http.connection.2834268344
Source: custom_components/plex_assistant/__init__.py:211
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 11:16:00 (1 occurrences)
Last logged: 11:16:00

(404) not_found; http://192.***.***.**:32400/player/playback/playMedia?address=192.***.***.**&commandID=1&containerKey=%2FplayQueues%2F264%3Fwindow%3D100%26own%3D1&key=%2Flibrary%2Fmetadata%2F640&machineIdentifier=616a7017caad7c46dcc59cd580adc7d6adf89596&offset=0&port=32400&token=transient-6ac90674-97f1-4573-b16b-5c95b7daf901&type=video <html><head><title>Not Found</title></head><body><h1>404 Not Found</h1></body></html>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 138, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1335, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1374, in _execute_service
    await self._hass.async_add_executor_job(handler.func, service_call)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/plex_assistant/__init__.py", line 211, in handle_input
    plex_c.playMedia(media)
  File "/usr/local/lib/python3.8/site-packages/plexapi/client.py", line 490, in playMedia
    self.sendCommand('playback/playMedia', **dict({
  File "/usr/local/lib/python3.8/site-packages/plexapi/client.py", line 208, in sendCommand
    return query(key, headers=headers)
  File "/usr/local/lib/python3.8/site-packages/plexapi/server.py", line 448, in query
    raise NotFound(message)
plexapi.exceptions.NotFound: (404) not_found; http://192.***.***.**:32400/player/playback/playMedia?address=192.***.***.**&commandID=1&containerKey=%2FplayQueues%2F264%3Fwindow%3D100%26own%3D1&key=%2Flibrary%2Fmetadata%2F640&machineIdentifier=616a7017caad7c46dcc59cd580adc7d6adf89596&offset=0&port=32400&token=transient-6ac90674-97f1-4573-b16b-5c95b7daf901&type=video <html><head><title>Not Found</title></head><body><h1>404 Not Found</h1></body></html>
```

**Comment by Drauboss** [comment]
Just checked and it works playing on chrome, but not on the Android tv Plex app and the Plex app on my phone

**Comment by maykar** [comment]
Is this still an issue, are the apps open on the TV/phone when you issue the command?

**Comment by regoras** [comment]
I know this just got marked as stale, but just got plex_assistant half-setup/working today and it does not seem to want to play to the Android TV app on my CC device (the new version with a remote), it will only play as a Cast. Haven't enabled debug logs to try to dig deeper, but just thought I'd echo @Drauboss that this doesn't seem to be working with the Android TV app.

**Comment by maykar** [comment]
Give the latest release a try and let me know if it helps. v0.3.3
