### ISSUE TITLE
Automation fails with `TypeError: expected string or bytes-like object`

### ISSUE THREAD

**Issue by mmnaseri** [maykar/plex_assistant#63]
When I issue a command like "play darker than black", this is what I get:

```
ERROR (MainThread) [homeassistant.components.automation.plex_assistant_automation] While executing automation automation.plex_assistant_automation
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 426, in async_trigger
    await self.action_script.async_run(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 985, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 239, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 247, in _async_step
    await getattr(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 454, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1335, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1374, in _execute_service
    await self._hass.async_add_executor_job(handler.func, service_call)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/plex_assistant/__init__.py", line 135, in handle_input
    device = fuzzy(command["device"] or default_cast, devices)
  File "/config/custom_components/plex_assistant/helpers.py", line 42, in fuzzy
    return fw.extractOne(media, lib, scorer=scorer)
  File "/usr/local/lib/python3.8/site-packages/fuzzywuzzy/process.py", line 220, in extractOne
    return max(best_list, key=lambda i: i[1])
  File "/usr/local/lib/python3.8/site-packages/fuzzywuzzy/process.py", line 78, in extractWithoutOrder
    processed_query = processor(query)
  File "/usr/local/lib/python3.8/site-packages/fuzzywuzzy/utils.py", line 95, in full_process
    string_out = StringProcessor.replace_non_letters_non_numbers_with_whitespace(s)
  File "/usr/local/lib/python3.8/site-packages/fuzzywuzzy/string_processing.py", line 26, in replace_non_letters_non_numbers_with_whitespace
    return cls.regex.sub(" ", a_string)
TypeError: expected string or bytes-like object
  File "/usr/local/lib/python3.8/site-packages/fuzzywuzzy/utils.py", line 95, in full_process
    string_out = StringProcessor.replace_non_letters_non_numbers_with_whitespace(s)
  File "/usr/local/lib/python3.8/site-packages/fuzzywuzzy/string_processing.py", line 26, in replace_non_letters_non_numbers_with_whitespace
    return cls.regex.sub(" ", a_string)
TypeError: expected string or bytes-like object
```

Basically the only command that doesn't result in these errors is `ask plex to update sensor`.

**Comment by mmnaseri** [comment]
Okay, I have figured out that this is because I have no `default_cast` set up. But shouldn't that be reported as an error? Thanks for the efforts! This is an awesome piece of software :)
