### ISSUE TITLE
Error on fresh install

### ISSUE THREAD

**Issue by fcastilloec** [maykar/plex_assistant#68]
After a first installation, I'm seeing a lot of errors. The token and URL are correct since Tautulli is also configured and working with Plex using the same token and URL. My server is configured to work only on secured connections, would that be the problem?

Here's the log output:

```
Logger: homeassistant.setup
Source: custom_components/plex_assistant/__init__.py:96
First occurred: 10:06:48 PM (1 occurrences)
Last logged: 10:06:48 PM

Error during setup of component plex_assistant
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 397, in connect
    _match_hostname(cert, self.assert_hostname or server_hostname)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 407, in _match_hostname
    match_hostname(cert, asserted_hostname)
  File "/usr/local/lib/python3.8/ssl.py", line 420, in match_hostname
    raise CertificateError("hostname %r "
ssl.SSLCertVerificationError: ("hostname '192.168.1.2' doesn't match '*.xxxxxxxxxxxxx.plex.direct'",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='192.168.1.2', port=32400): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError("hostname '192.168.1.2' doesn't match '*.xxxxxxxxxxxxx.plex.direct'")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/config/custom_components/plex_assistant/__init__.py", line 100, in async_setup
    await hass.async_add_executor_job(sync_io_server, base_url, token)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/plex_assistant/__init__.py", line 96, in sync_io_server
    PA.server = PlexServer(base_url, token)
  File "/usr/local/lib/python3.8/site-packages/plexapi/server.py", line 110, in __init__
    data = self.query(self.key, timeout=timeout)
  File "/usr/local/lib/python3.8/site-packages/plexapi/server.py", line 440, in query
    response = method(url, headers=headers, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='192.168.1.2', port=32400): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError("hostname '192.168.1.2' doesn't match '*.xxxxxxxxxxxxx.plex.direct'")))
```

**Comment by maykar** [comment]
Yes, that would be the problem. The SSL certificate You either need to set secured connections to "preferred" in Plex's network settings, use the plex.direct URL in your config, or if you use a custom SSL certificate use the URL that certificate is for in your config.

**Comment by fcastilloec** [comment]
I rather not change my connections to preferred, I want to keep all my connections secured all the time. I also don't use any custom SSL certificate, the certificate is the one assigned by Plex itself but when using from inside a LAN with an IP address, the error happens.

> use the plex.direct URL

I wasn't really sure what you mean by this. I remember seeing something like this when looking for my token. I used this address and the error went away. I suggest there's a mention of using this URL (and how to find it) when a Plex server is setup for secured connections only.

**Comment by maykar** [comment]
I have never had to use the plex.direct URL and don't know much about it myself. I just looked at your error, the part that reads:

```
hostname '192.168.1.2' doesn't match '*.xxxxxxxxxxxxx.plex.direct'
```

That is why I suggested using that URL. If you have further information feel free to update the docs yourself or provide the information here so that others may benefit. After a quick search, I don't see anything in plex's docs about where to find your plex.direct URL.

**Comment by fcastilloec** [comment]
For anybody else that lands here with the same problem, just follow the tutorial to retrieve your token https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/ but make sure you got to https://plex.tv and not your localhost or IP address.

Once you've seen the following picture
![xml_info_token](https://user-images.githubusercontent.com/1280530/99594764-7ccd3580-29a8-11eb-916c-0d52acc03b16.png)
The URL will look something like `https://192-168-10-25.xxxxxxxxxxxxxxxxx.plex.direct:32400/`
Where the first part (192-168-10-25) is the local IP address of the Plex server, and `xxxxxxxxxxxxxxxxx` are some random numbers and letters. Probably the ID that identifies your server on the Internet.

Feel free to use this info on the README, otherwise, I'll try to submit a PR with these details when I have a chance.

**Comment by maykar** [comment]
Ah okay, not too bad. So:

* Go to https://app.plex.tv/ and sign in.
* Hit the vertical 3 dots on any media item (episode, movie, etc)
* Select "Get Info", then click "View XML"
* The URL field of your browser now contains your plex.direct URL
* Copy everything before "library"
* It will look something like this: `https://192-168-10-25.xxxxxxxxxxxxxxxxx.plex.direct:32400/`

**Comment by maykar** [comment]
Updated the readme and will add this to the Plex Upcoming Media integrations readme as well. Thank you!
