### ISSUE TITLE
Error when attempting to cast media

### ISSUE THREAD

**Issue by oysteinkrog** [maykar/plex_assistant#76]
Latest stable everything as of today (Home Assistant 2021.1.1) running on a hassos raspi.

`2021-01-13 16:59:00 ERROR (Thread-94) [pychromecast.socket_client] [MIBOX3(192.168.1.180):8009] Exception caught while sending message to controller ReceiverController: Message urn:x-cast:com.google.cast.receiver from receiver-0 to *: {'requestId': 4, 'status': {'applications': [{'appId': '9AC194DC', 'appType': 'WEB', 'displayName': 'Plex', 'iconUrl': 'http://lh3.ggpht.com/F-carnehpMLNP_IxDt3-IhX9qlnPZcgnC1Ri8E9xkkkIWoeWI_GcD5ZeIQlNkKblg2jOvZLHUm-metNK', 'isIdleScreen': False, 'launchedFromCloud': False, 'namespaces': [{'name': 'urn:x-cast:com.google.cast.debugoverlay'}, {'name': 'urn:x-cast:com.google.cast.cac'}, {'name': 'urn:x-cast:plex'}, {'name': 'urn:x-cast:com.google.cast.broadcast'}, {'name': 'urn:x-cast:com.google.cast.media'}], 'sessionId': 'fb11e017-cd44-46ec-8f43-b6232d5284ce', 'statusText': 'Plex', 'transportId': 'fb11e017-cd44-46ec-8f43-b6232d5284ce', 'universalAppId': '9AC194DC'}], 'isActiveInput': True, 'isStandBy': False, 'userEq': {}, 'volume': {'controlType': 'attenuation', 'level': 0.46666666865348816, 'muted': False, 'stepInterval': 0.06666667014360428}}, 'type': 'RECEIVER_STATUS'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pychromecast/socket_client.py", line 707, in _route_message
    handled = self._handlers[message.namespace].receive_message(
  File "/usr/local/lib/python3.8/site-packages/pychromecast/socket_client.py", line 1140, in receive_message
    self._process_get_status(data)
  File "/usr/local/lib/python3.8/site-packages/pychromecast/socket_client.py", line 1272, in _process_get_status
    self.app_launch_event_function()
  File "/usr/local/lib/python3.8/site-packages/pychromecast/controllers/plex.py", line 449, in app_launched_callback
    self._send_start_play(media, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pychromecast/controllers/plex.py", line 406, in _send_start_play
    msg = media_to_chromecast_command(
  File "/usr/local/lib/python3.8/site-packages/pychromecast/controllers/plex.py", line 97, in media_to_chromecast_command
    server = media[0]._server if isinstance(media, list) else media._server
AttributeError: 'str' object has no attribute '_server'`

`2021-01-13 16:55:20 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [1764579120] 'str' object has no attribute '_server'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 135, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1445, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1484, in _execute_service
    await self._hass.async_add_executor_job(handler.job.target, service_call)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/plex_assistant/__init__.py", line 215, in handle_input
    plex_c.block_until_playing(media)
  File "/usr/local/lib/python3.8/site-packages/pychromecast/controllers/plex.py", line 433, in block_until_playing
    self.play_media(media, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pychromecast/controllers/plex.py", line 453, in play_media
    self.launch(app_launched_callback)
  File "/usr/local/lib/python3.8/site-packages/pychromecast/controllers/__init__.py", line 44, in launch
    self._socket_client.receiver_controller.launch_app(
  File "/usr/local/lib/python3.8/site-packages/pychromecast/socket_client.py", line 1183, in launch_app
    self._send_launch_message(app_id, force_launch, callback_function)
  File "/usr/local/lib/python3.8/site-packages/pychromecast/socket_client.py", line 1198, in _send_launch_message
    callback_function()
  File "/usr/local/lib/python3.8/site-packages/pychromecast/controllers/plex.py", line 449, in app_launched_callback
    self._send_start_play(media, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pychromecast/controllers/plex.py", line 406, in _send_start_play
    msg = media_to_chromecast_command(
  File "/usr/local/lib/python3.8/site-packages/pychromecast/controllers/plex.py", line 97, in media_to_chromecast_command
    server = media[0]._server if isinstance(media, list) else media._server
AttributeError: 'str' object has no attribute '_server'`

**Comment by maykar** [comment]
Could you enable debug info for the component in configuration.yaml to see if we can get a bit more insight into what's happening here?

```
logger:
  logs:
    custom_components.plex_assistant: debug
```

**Comment by maykar** [comment]
I've also made a new [Troubleshooting Guide](https://github.com/maykar/plex_assistant/blob/master/troubleshooting.md) that would be worth a look.
